version: '2'

networks:
    app-tier:
        driver: bridge

services:
    etcd:
        container_name: "etcd_goApp"
        image: 'bitnami/etcd:latest'
        environment: 
            - ALLOW_NONE_AUTHENTICATION=yes
            - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
        ports:
            - 2379:2379
            - 2380:2380
        networks:
            - app-tier
    myapp:
        #image: 'guilherme/go1:latest'
        container_name: "goApp"
        build: .
        command: go run go-homework.go
        ports:
            - "8080:8080"
        volumes:
            - .:/app
        networks:
            - app-tier